services:
  campusdock:
    image: ritikkumar352/campusdock:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: campusdock-app
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
