services:
  campusdock:
    image: ritikkumar352/campusdock:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: campusdock-app
    ports:
      - "8082:8081"  # 81 inside container 82 exposed
    restart: always
    env_file:
      - .env
